spring:
  application:
    name: swgoh

  datasource:
    url: jdbc:${DB_URL}?reWriteBatchedInserts=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 15

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true

  web:
    locale: fr_FR
    locale-resolver: fixed

logging:
  level:
    swgohManager: DEBUG

swgoh:
  api:
    base-url: http://localhost:3200
  guild:
    id: PzZXMmXISCG8tP9Blinblw
  comlink:
    image: ghcr.io/swgoh-utils/swgoh-comlink:latest
    container-name: swgoh-comlink
    app-name: my_swgoh
    port: 3200

admin:
  password: ${ADMIN_PASSWORD:BaguettesEnflamées!}

app:
  import:
    directory: ./imports